### ISSUE TITLE
Help generating the .tags file

### ISSUE THREAD

**Issue by nathansandri** [jaydenlin/ctags-support#11]
How do i run the command to generate the tag file.  I have installed the extension but it does not recognize the ctags command.  I am trying to use this in visual studio code on fedora 23 if that helps.  Thanks.

**Comment by kroppt** [comment]
Did you actually install `ctags`? It does not come with the extension.

**Comment by jaydenlin** [comment]
Hi @techhector,
You have to follow the guide here to install ctags before you use the extension :) 
http://ctags.sourceforge.net/
