### ISSUE TITLE
Specify tag file

### ISSUE THREAD

**Issue by magikid** [jaydenlin/ctags-support#14]
It would be nice if there were a configuration option to set the name of the tag file.  I keep my ctags file in .git/tags.  This plugin in its current state is unusable for me since I can't tell it to use my actual tag file.

**Comment by boekhoffm** [comment]
Yes, is there any way to get it to search for the tags file in the heirarchy in and above the current file?

**Comment by KiranHappy** [comment]
over windows ctag tool generate 'tags' not '.tags', 
thus to use this plugin , every time need to rename the file.
Better if we had this feature of mentioning tag file name

**Comment by egk696** [comment]
This is a must to have, working on large projects where the codebase is remote and people use different editors that support custom locations of 'tags' means that the only way to use this plugin is to copy the file locally everytime.

**Comment by jaydenlin** [comment]
the issue is resolved.
https://github.com/jaydenlin/ctags-support/pull/21
credit to @practically-illiterate 
thanks
